import "bootstrap/dist/css/bootstrap.css";
import "@styles/globals.css";
import '@fortawesome/fontawesome-svg-core/styles.css';
import { Montserrat } from "next/font/google";
import Footer from "@components/Footer";
import NavBar from "@components/NavBar";
// import Providers from "./providers";
import { config } from '@fortawesome/fontawesome-svg-core';
config.autoAddCss = false; 

export const montserrat = Montserrat({
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});
export const metadata = {
  title: "1Trolley Cloud",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        {/* <Providers> */}
          <NavBar />
          {children}
          <Footer />
        {/* </Providers> */}
      </body>
    </html>
  );
}
